### ISSUE TITLE
Error: Version '1.5.*' for 'python-pip' was not found

### ISSUE THREAD

**Issue by allomov** [azavea/ansible-pip#3]
Hello. 

I try to run `azavea.golang` on ubuntu 16.04 and get this error message:
```
TASK [azavea.build-essential : Install build-essential] ************************
ok: [localhost]

TASK [azavea.git : Install Git] ************************************************
ok: [localhost]

TASK [azavea.pip : Install pip] ************************************************
fatal: [localhost]: FAILED! => {"cache_update_time": 0, "cache_updated": false, "changed": false, "failed": true, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"   install 'python-pip=1.5.*'' failed: E: Version '1.5.*' for 'python-pip' was not found\n", "stderr": "E: Version '1.5.*' for 'python-pip' was not found\n", "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information..."]}

PLAY RECAP *********************************************************************
localhost                  : ok=15   changed=0    unreachable=0    failed=1
```

I have Python 2.7.12 and Ansible 2.0 (I tried with 2.2 and got the same result) installed on this VM. I can also install python-pip with `sudo apt-get instal python-pip` (`pip -V` shows `pip 8.1.1 from /usr/lib/python2.7/dist-packages (python 2.7)`).

**Comment by hectcastro** [comment]
Hey @allomov,

The role defaults are setup to work out of the box for Ubuntu 14.04. If you override the `pip_version` variable with something like `8.1.*`, it should install `pip` successfully.

**Comment by allomov** [comment]
@hectcastro thank you for answer.

I've tried. Still it had the same issue: it tells me it can't find version `8.1.*`, at the same time I have the version `8.1.1` of `python-pip` installed on this VM.

**Comment by allomov** [comment]
I fixed this issue by adding the following variable to my role:
```
- role: azavea.golang
  ...
  pip_version: "8.1.*"
  python_version: "2.7.*"

```
Do you think defaults for `azavea.pip` and `azavea.python` can be updated?

**Comment by allomov** [comment]
adding `pip_version: "8.1.*"` broke tests for ubuntu 14.04
